clone_folder: c:\projects\calculator
clone_depth: 2

platform: x64

environment:
  matrix:
  - PYTHON: "C:\\Python36-x64"

cache:
- C:\Users\appveyor\pip\wheels
- '%LOCALAPPDATA%\pip\Cache'

install:
- "%PYTHON%\\python.exe -m pip install -U pip"
- "%PYTHON%\\python.exe -m pip install pyglet pytest pyinstaller"

build: off

test_script:
- "%PYTHON%\\python.exe -m pytest tests"

after_test:
- "%PYTHON%\\python.exe -m PyInstaller __main__.py -n calculator-app --exclude-module tkinter --add-data calculator;calculator -F -w"

artifacts:
- path: dist\*